# Generated by Django 5.1.5 on 2025-01-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='链接文字内容')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='分组')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('department', models.CharField(max_length=255, verbose_name='科室')),
                ('origin_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属医院科室')),
                ('project', models.CharField(blank=True, max_length=255, null=True, verbose_name='帮扶项目')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='职称')),
                ('duty', models.CharField(blank=True, max_length=255, null=True, verbose_name='职务')),
                ('talent', models.CharField(blank=True, max_length=255, null=True, verbose_name='专业特长')),
                ('official_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='坐诊时间')),
                ('contactor', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
